In [1]:
import pandas as pd

employees = pd.DataFrame({
'Emp_ID':[101,102,103,104,105,106,107,108],
'Name':['Vinay','Aman','Riya','Priya','Karan','Neha','Rahul','Pooja'],
'Department':['IT','HR','IT','Sales','HR','Sales','IT','Finance'],
'Salary':[50000,45000,60000,55000,48000,65000,70000,80000]
})


employees

   Emp_ID   Name Department  Salary
0     101  Vinay         IT   50000
1     102   Aman         HR   45000
2     103   Riya         IT   60000
3     104  Priya      Sales   55000
4     105  Karan         HR   48000
5     106   Neha      Sales   65000
6     107  Rahul         IT   70000
7     108  Pooja    Finance   80000

In [2]:
bonus = pd.DataFrame({
'Emp_ID':[101,102,103,105,109],
'Bonus':[5000,3000,7000,4000,6000]
})
bonus

   Emp_ID  Bonus
0     101   5000
1     102   3000
2     103   7000
3     105   4000
4     109   6000

In [3]:
jan_emp = pd.DataFrame({
'Emp_ID':[101,102,103],
'Name':['Vinay','Aman','Riya']
})

jan_emp

   Emp_ID   Name
0     101  Vinay
1     102   Aman
2     103   Riya

In [4]:
feb_emp = pd.DataFrame({
'Emp_ID':[104,105,106],
'Name':['Priya','Karan','Neha']
})

feb_emp

   Emp_ID   Name
0     104  Priya
1     105  Karan
2     106   Neha

##  GroupBy Questions

* Basic GroupBy

1. Group employees by Department.

2. Count employees in each department.

3. Find total salary paid department-wise.

4. Find average salary department-wise.

5. Find maximum salary department-wise.

6. Find minimum salary department-wise.

In [5]:
employees.groupby('Department')

In [6]:
employees.groupby('Department').count()

            Emp_ID  Name  Salary
Department
Finance          1     1       1
HR               2     2       2
IT               3     3       3
Sales            2     2       2

In [7]:
employees.groupby('Department')['Salary'].sum()

Department
Finance     80000
HR          93000
IT         180000
Sales      120000
Name: Salary, dtype: int64

In [8]:
employees.groupby('Department')['Salary'].median()

Department
Finance    80000.0
HR         46500.0
IT         60000.0
Sales      60000.0
Name: Salary, dtype: float64

In [9]:
employees.groupby('Department')['Salary'].max()

Department
Finance    80000
HR         48000
IT         70000
Sales      65000
Name: Salary, dtype: int64

In [10]:
employees.groupby('Department')['Salary'].min()

Department
Finance    80000
HR         45000
IT         50000
Sales      55000
Name: Salary, dtype: int64

## Aggregation Questions

7. Find the total salary of all IT employees.

8. Find the average salary of HR employees.

9. Find the highest salary in Sales department.

10. Find the number of employees in each department.

In [11]:
employees[employees['Department']=='IT']['Salary'].sum()

np.int64(180000)

In [12]:
employees[employees['Department']=='HR']['Salary'].median()

np.float64(46500.0)

In [13]:
employees[employees['Department']=='Sales']['Salary'].max()

np.int64(65000)

In [14]:
employees.groupby('Department').count()

            Emp_ID  Name  Salary
Department
Finance          1     1       1
HR               2     2       2
IT               3     3       3
Sales            2     2       2

In [15]:
employees['Department'].value_counts()

Department
IT         3
HR         2
Sales      2
Finance    1
Name: count, dtype: int64

## Multiple Aggregation Questions

11. For each department show:

Sum of salary

Average salary

Maximum salary

Minimum salary

12. Generate a department-wise salary report containing:

count

mean

max

min

13. Which department has the highest average salary?

14. Which department has the highest total salary expenditure?

15. Which department has the maximum number of employees?

In [16]:
employees.groupby('Department')['Salary'].agg(['sum','mean','max','min'])

               sum     mean    max    min
Department
Finance      80000  80000.0  80000  80000
HR           93000  46500.0  48000  45000
IT          180000  60000.0  70000  50000
Sales       120000  60000.0  65000  55000

In [17]:
employees.groupby('Department')['Salary'].mean().idxmax()

'Finance'

In [18]:
employees.groupby('Department')['Salary'].agg(['count','mean','max','min'])

            count     mean    max    min
Department
Finance         1  80000.0  80000  80000
HR              2  46500.0  48000  45000
IT              3  60000.0  70000  50000
Sales           2  60000.0  65000  55000

In [19]:
employees.groupby('Department')['Salary'].sum().idxmax()

'IT'

In [20]:
employees['Department'].value_counts()

Department
IT         3
HR         2
Sales      2
Finance    1
Name: count, dtype: int64

## Merge Questions

* Inner Join

16. Merge employees and bonus tables using Inner Join.

17. How many employees received bonuses?

18. Find employee names along with their bonus amounts.

* Left Join

19. Show all employees and their bonuses.

20. Identify employees who did not receive a bonus.

21. Count employees whose bonus is missing.

* Right Join

22. Show all bonus records even if employee information is missing.

23. Identify bonus records that do not have matching employee details.

* Outer Join

24. Merge both tables using Outer Join.

25. Find records present only in the employee table.

26. Find records present only in the bonus table.

27. Identify all mismatched records.

In [21]:
pd.merge(employees,bonus, how='inner')

   Emp_ID   Name Department  Salary  Bonus
0     101  Vinay         IT   50000   5000
1     102   Aman         HR   45000   3000
2     103   Riya         IT   60000   7000
3     105  Karan         HR   48000   4000

In [22]:
merged = pd.merge(employees, bonus, on='Emp_ID', how='inner')
merged['Emp_ID'].nunique()

4

In [23]:
merged[['Name','Bonus']]

    Name  Bonus
0  Vinay   5000
1   Aman   3000
2   Riya   7000
3  Karan   4000

In [25]:
pd.merge(employees,bonus, how='left')

   Emp_ID   Name Department  Salary   Bonus
0     101  Vinay         IT   50000  5000.0
1     102   Aman         HR   45000  3000.0
2     103   Riya         IT   60000  7000.0
3     104  Priya      Sales   55000     NaN
4     105  Karan         HR   48000  4000.0
5     106   Neha      Sales   65000     NaN
6     107  Rahul         IT   70000     NaN
7     108  Pooja    Finance   80000     NaN

In [36]:
join = pd.merge(employees,bonus, how='left')
join[join['Bonus'].isnull()]

   Emp_ID   Name Department  Salary  Bonus
3     104  Priya      Sales   55000    NaN
5     106   Neha      Sales   65000    NaN
6     107  Rahul         IT   70000    NaN
7     108  Pooja    Finance   80000    NaN

In [35]:
no_bonus = employees.merge(bonus, how='left')
no_bonus = no_bonus[no_bonus['Bonus'].isnull()]
print(no_bonus)

   Emp_ID   Name Department  Salary  Bonus
3     104  Priya      Sales   55000    NaN
5     106   Neha      Sales   65000    NaN
6     107  Rahul         IT   70000    NaN
7     108  Pooja    Finance   80000    NaN

In [39]:
count_no_bonus = join[join['Bonus'].isnull()].shape[0]
count_no_bonus

4

In [41]:
pd.merge(bonus,employees, how='right')

   Emp_ID   Bonus   Name Department  Salary
0     101  5000.0  Vinay         IT   50000
1     102  3000.0   Aman         HR   45000
2     103  7000.0   Riya         IT   60000
3     104     NaN  Priya      Sales   55000
4     105  4000.0  Karan         HR   48000
5     106     NaN   Neha      Sales   65000
6     107     NaN  Rahul         IT   70000
7     108     NaN  Pooja    Finance   80000

In [47]:
right_join = employees.merge(bonus, how='right')
right_join

   Emp_ID   Name Department   Salary  Bonus
0     101  Vinay         IT  50000.0   5000
1     102   Aman         HR  45000.0   3000
2     103   Riya         IT  60000.0   7000
3     105  Karan         HR  48000.0   4000
4     109    NaN        NaN      NaN   6000

In [ ]:
right_join[right_join['Name'].isnull()]

   Emp_ID Name Department  Salary  Bonus
4     109  NaN        NaN     NaN   6000

In [52]:
outer_join = employees.merge(bonus, on='Emp_ID', how='outer')
outer_join

   Emp_ID   Name Department   Salary   Bonus
0     101  Vinay         IT  50000.0  5000.0
1     102   Aman         HR  45000.0  3000.0
2     103   Riya         IT  60000.0  7000.0
3     104  Priya      Sales  55000.0     NaN
4     105  Karan         HR  48000.0  4000.0
5     106   Neha      Sales  65000.0     NaN
6     107  Rahul         IT  70000.0     NaN
7     108  Pooja    Finance  80000.0     NaN
8     109    NaN        NaN      NaN  6000.0

In [54]:
outer_join[outer_join['Bonus'].isnull()]

   Emp_ID   Name Department   Salary  Bonus
3     104  Priya      Sales  55000.0    NaN
5     106   Neha      Sales  65000.0    NaN
6     107  Rahul         IT  70000.0    NaN
7     108  Pooja    Finance  80000.0    NaN

In [55]:
outer_join[outer_join['Bonus'].notnull()]

   Emp_ID   Name Department   Salary   Bonus
0     101  Vinay         IT  50000.0  5000.0
1     102   Aman         HR  45000.0  3000.0
2     103   Riya         IT  60000.0  7000.0
4     105  Karan         HR  48000.0  4000.0
8     109    NaN        NaN      NaN  6000.0

In [59]:
mismatched = outer_join[(outer_join['Name'].isnull()) | (outer_join['Bonus'].isnull())]
mismatched

   Emp_ID   Name Department   Salary   Bonus
3     104  Priya      Sales  55000.0     NaN
5     106   Neha      Sales  65000.0     NaN
6     107  Rahul         IT  70000.0     NaN
7     108  Pooja    Finance  80000.0     NaN
8     109    NaN        NaN      NaN  6000.0

## Concat Questions

* Vertical Concatenation

28. Combine January and February employee data vertically.

29. After concatenation, find the total number of employees.

30. Reset the index after concatenation.

31. Add March employee data and concatenate all three months.

* Horizontal Concatenation

Create another dataframe:


salary_info = pd.DataFrame({
'Experience':[2,1,4,3,5,6,7,8],
'City':['Jaipur','Delhi','Mumbai','Pune',
'Delhi','Jaipur','Mumbai','Pune']
})


32. Concatenate employees and salary_info horizontally.

33. Display employee names along with cities.

34. Display employee names and experience.

35. Count employees city-wise.

In [62]:
employees

   Emp_ID   Name Department  Salary
0     101  Vinay         IT   50000
1     102   Aman         HR   45000
2     103   Riya         IT   60000
3     104  Priya      Sales   55000
4     105  Karan         HR   48000
5     106   Neha      Sales   65000
6     107  Rahul         IT   70000
7     108  Pooja    Finance   80000

In [60]:
feb_emp

   Emp_ID   Name
0     104  Priya
1     105  Karan
2     106   Neha

In [61]:
jan_emp

   Emp_ID   Name
0     101  Vinay
1     102   Aman
2     103   Riya

In [67]:
emp_jan_fab = pd.concat([jan_emp,feb_emp], axis=0)
emp_jan_fab

   Emp_ID   Name
0     101  Vinay
1     102   Aman
2     103   Riya
0     104  Priya
1     105  Karan
2     106   Neha

In [69]:
emp_jan_fab.shape

(6, 2)

In [70]:
emp_jan_fab.shape[0]

6

In [ ]:
emp_reset_index = emp_jan_fab.reset_index(drop=True)
emp_reset_index

   Emp_ID   Name
0     101  Vinay
1     102   Aman
2     103   Riya
3     104  Priya
4     105  Karan
5     106   Neha

In [72]:
salary_info = pd.DataFrame({
'Experience':[2,1,4,3,5,6,7,8],
'City':['Jaipur','Delhi','Mumbai','Pune',
'Delhi','Jaipur','Mumbai','Pune']
})

In [73]:
salary_info

   Experience    City
0           2  Jaipur
1           1   Delhi
2           4  Mumbai
3           3    Pune
4           5   Delhi
5           6  Jaipur
6           7  Mumbai
7           8    Pune

In [78]:
emp_all = pd.concat([jan_emp, feb_emp, salary_info], axis=  1)

In [79]:
emp_all

   Emp_ID   Name  Emp_ID   Name  Experience    City
0   101.0  Vinay   104.0  Priya           2  Jaipur
1   102.0   Aman   105.0  Karan           1   Delhi
2   103.0   Riya   106.0   Neha           4  Mumbai
3     NaN    NaN     NaN    NaN           3    Pune
4     NaN    NaN     NaN    NaN           5   Delhi
5     NaN    NaN     NaN    NaN           6  Jaipur
6     NaN    NaN     NaN    NaN           7  Mumbai
7     NaN    NaN     NaN    NaN           8    Pune

In [84]:
emp_salary_info = pd.concat([employees,salary_info], axis=1).reset_index(drop=True)
emp_salary_info

   Emp_ID   Name Department  Salary  Experience    City
0     101  Vinay         IT   50000           2  Jaipur
1     102   Aman         HR   45000           1   Delhi
2     103   Riya         IT   60000           4  Mumbai
3     104  Priya      Sales   55000           3    Pune
4     105  Karan         HR   48000           5   Delhi
5     106   Neha      Sales   65000           6  Jaipur
6     107  Rahul         IT   70000           7  Mumbai
7     108  Pooja    Finance   80000           8    Pune

In [86]:
emp_salary_info[['Name','City']]

    Name    City
0  Vinay  Jaipur
1   Aman   Delhi
2   Riya  Mumbai
3  Priya    Pune
4  Karan   Delhi
5   Neha  Jaipur
6  Rahul  Mumbai
7  Pooja    Pune

In [87]:
emp_salary_info[['Name','Experience']]

    Name  Experience
0  Vinay           2
1   Aman           1
2   Riya           4
3  Priya           3
4  Karan           5
5   Neha           6
6  Rahul           7
7  Pooja           8

In [88]:
count_epm_citywise = emp_salary_info.groupby('City')['Name'].count()
count_epm_citywise

City
Delhi     2
Jaipur    2
Mumbai    2
Pune      2
Name: Name, dtype: int64

## Join Questions

Convert Emp_ID into index.

emp_index = employees.set_index('Emp_ID')
bonus_index = bonus.set_index('Emp_ID')

36. Join employee and bonus datasets.

37. Find employees whose bonus is missing.

38. Find employees who received bonuses.

39. Count employees having bonus greater than 5000.

40. Replace missing bonuses with 0 after joining.

Real-World Case Study

The HR department wants a report.

Perform the following:

1. Group employees by department.

2. Calculate:

Total salary

Average salary

Maximum salary

Minimum salary

3. Merge employee and bonus data.

4. Identify employees without bonuses.

5. Combine January and February employee records
.
6. Generate a final report showing:

Employee Name

Department

Salary

Bonus

Total Compensation (Salary + Bonus)

In [89]:
emp_index = employees.set_index('Emp_ID')
bonus_index = bonus.set_index('Emp_ID')

In [92]:
emp_bonus = emp_index.join(bonus_index, how='left')
emp_bonus

         Name Department  Salary   Bonus
Emp_ID
101     Vinay         IT   50000  5000.0
102      Aman         HR   45000  3000.0
103      Riya         IT   60000  7000.0
104     Priya      Sales   55000     NaN
105     Karan         HR   48000  4000.0
106      Neha      Sales   65000     NaN
107     Rahul         IT   70000     NaN
108     Pooja    Finance   80000     NaN

In [93]:
emp_bonus[emp_bonus['Bonus'].isnull()]

         Name Department  Salary  Bonus
Emp_ID
104     Priya      Sales   55000    NaN
106      Neha      Sales   65000    NaN
107     Rahul         IT   70000    NaN
108     Pooja    Finance   80000    NaN

In [94]:
emp_bonus[emp_bonus['Bonus'].notnull()]

         Name Department  Salary   Bonus
Emp_ID
101     Vinay         IT   50000  5000.0
102      Aman         HR   45000  3000.0
103      Riya         IT   60000  7000.0
105     Karan         HR   48000  4000.0

In [99]:
(emp_bonus['Bonus'] > 5000).sum()

np.int64(1)

In [ ]:
emp_bonus.fillna({'Bonus':0})

         Name Department  Salary   Bonus
Emp_ID
101     Vinay         IT   50000  5000.0
102      Aman         HR   45000  3000.0
103      Riya         IT   60000  7000.0
104     Priya      Sales   55000     0.0
105     Karan         HR   48000  4000.0
106      Neha      Sales   65000     0.0
107     Rahul         IT   70000     0.0
108     Pooja    Finance   80000     0.0

In [101]:
dept_group = employees.groupby('Department')
dept_group

In [102]:
dept_group['Salary'].agg(['sum','mean','max','min'])

               sum     mean    max    min
Department
Finance      80000  80000.0  80000  80000
HR           93000  46500.0  48000  45000
IT          180000  60000.0  70000  50000
Sales       120000  60000.0  65000  55000

In [104]:
emp_bonus_report = employees.merge(bonus, on='Emp_ID', how='left')
emp_bonus_report

   Emp_ID   Name Department  Salary   Bonus
0     101  Vinay         IT   50000  5000.0
1     102   Aman         HR   45000  3000.0
2     103   Riya         IT   60000  7000.0
3     104  Priya      Sales   55000     NaN
4     105  Karan         HR   48000  4000.0
5     106   Neha      Sales   65000     NaN
6     107  Rahul         IT   70000     NaN
7     108  Pooja    Finance   80000     NaN

In [105]:
emp_bonus_report[emp_bonus_report['Bonus'].isnull()]

   Emp_ID   Name Department  Salary  Bonus
3     104  Priya      Sales   55000    NaN
5     106   Neha      Sales   65000    NaN
6     107  Rahul         IT   70000    NaN
7     108  Pooja    Finance   80000    NaN

In [109]:
emp_jan_feb = pd.concat([jan_emp, feb_emp], axis=0).reset_index(drop=True)
emp_jan_fab

   Emp_ID   Name
0     101  Vinay
1     102   Aman
2     103   Riya
0     104  Priya
1     105  Karan
2     106   Neha

In [111]:
final_report = emp_bonus_report.fillna({'Bonus':0})
final_report['Total_Compensation'] = final_report['Salary'] + final_report['Bonus']
final_report[['Name','Department','Salary','Bonus','Total_Compensation']]

    Name Department  Salary   Bonus  Total_Compensation
0  Vinay         IT   50000  5000.0             55000.0
1   Aman         HR   45000  3000.0             48000.0
2   Riya         IT   60000  7000.0             67000.0
3  Priya      Sales   55000     0.0             55000.0
4  Karan         HR   48000  4000.0             52000.0
5   Neha      Sales   65000     0.0             65000.0
6  Rahul         IT   70000     0.0             70000.0
7  Pooja    Finance   80000     0.0             80000.0