In [2]:
import pandas as pd

df = pd.DataFrame({
    'Emp_ID': [101, 102, 103, 104, 105],
    'Name': ['Vinay', 'Aman', 'Riya', 'Priya', 'Karan'],
    'Department': ['IT', 'HR', 'IT', 'Sales', 'Finance'],
    'Salary': [50000, 45000, 60000, 55000, 70000],
    'Experience': [2, 1, 4, 3, 5]
})

df

   Emp_ID   Name Department  Salary  Experience
0     101  Vinay         IT   50000           2
1     102   Aman         HR   45000           1
2     103   Riya         IT   60000           4
3     104  Priya      Sales   55000           3
4     105  Karan    Finance   70000           5

In [3]:
# add a new columns name bonus 
df['Bonuse'] = df['Salary']
df

   Emp_ID   Name Department  Salary  Experience  Bonuse
0     101  Vinay         IT   50000           2   50000
1     102   Aman         HR   45000           1   45000
2     103   Riya         IT   60000           4   60000
3     104  Priya      Sales   55000           3   55000
4     105  Karan    Finance   70000           5   70000

In [4]:
df['Total_salary'] = df['Salary'] + 5000
df

   Emp_ID   Name Department  Salary  Experience  Bonuse  Total_salary
0     101  Vinay         IT   50000           2   50000         55000
1     102   Aman         HR   45000           1   45000         50000
2     103   Riya         IT   60000           4   60000         65000
3     104  Priya      Sales   55000           3   55000         60000
4     105  Karan    Finance   70000           5   70000         75000

In [5]:
df['Tax'] = df['Salary'] *0.10
df

   Emp_ID   Name Department  Salary  Experience  Bonuse  Total_salary     Tax
0     101  Vinay         IT   50000           2   50000         55000  5000.0
1     102   Aman         HR   45000           1   45000         50000  4500.0
2     103   Riya         IT   60000           4   60000         65000  6000.0
3     104  Priya      Sales   55000           3   55000         60000  5500.0
4     105  Karan    Finance   70000           5   70000         75000  7000.0

In [6]:
df.drop(columns='Bonuse')

   Emp_ID   Name Department  Salary  Experience  Total_salary     Tax
0     101  Vinay         IT   50000           2         55000  5000.0
1     102   Aman         HR   45000           1         50000  4500.0
2     103   Riya         IT   60000           4         65000  6000.0
3     104  Priya      Sales   55000           3         60000  5500.0
4     105  Karan    Finance   70000           5         75000  7000.0

In [7]:
# drop the bonuse columns
df.drop('Bonuse', axis=1, inplace=True)

In [8]:
df

   Emp_ID   Name Department  Salary  Experience  Total_salary     Tax
0     101  Vinay         IT   50000           2         55000  5000.0
1     102   Aman         HR   45000           1         50000  4500.0
2     103   Riya         IT   60000           4         65000  6000.0
3     104  Priya      Sales   55000           3         60000  5500.0
4     105  Karan    Finance   70000           5         75000  7000.0

In [ ]:
# sorting the values based on columns
df.sort_values(by='Salary')

   Emp_ID   Name Department  Salary  Experience  Total_salary     Tax
1     102   Aman         HR   45000           1         50000  4500.0
0     101  Vinay         IT   50000           2         55000  5000.0
3     104  Priya      Sales   55000           3         60000  5500.0
2     103   Riya         IT   60000           4         65000  6000.0
4     105  Karan    Finance   70000           5         75000  7000.0

In [11]:
df.sort_values(by = ['Salary', 'Total_salary'], ascending=False)

   Emp_ID   Name Department  Salary  Experience  Total_salary     Tax
4     105  Karan    Finance   70000           5         75000  7000.0
2     103   Riya         IT   60000           4         65000  6000.0
3     104  Priya      Sales   55000           3         60000  5500.0
0     101  Vinay         IT   50000           2         55000  5000.0
1     102   Aman         HR   45000           1         50000  4500.0

### String manupulstion on the Dataset

In [36]:
import pandas as pd

df = pd.DataFrame({
    'Emp_ID':[101,102,103,104,105],
    'Name':['VINAY SHARMA','aman gupta','RIYA VERMA','Priya Singh','KARAN JAIN'],
    'Email':[
        'vinay@gmail.com',
        'aman@yahoo.com',
        'riya@gmail.com',
        'priya@outlook.com',
        'karan@yahoo.com'
    ],
    'Department':['IT','HR','IT','Sales','Finance'],
    'Salary':[50000,45000,60000,55000,70000]
})

df

   Emp_ID          Name              Email Department  Salary
0     101  VINAY SHARMA    vinay@gmail.com         IT   50000
1     102    aman gupta     aman@yahoo.com         HR   45000
2     103    RIYA VERMA     riya@gmail.com         IT   60000
3     104   Priya Singh  priya@outlook.com      Sales   55000
4     105    KARAN JAIN    karan@yahoo.com    Finance   70000

df['Name'].str.upper()

In [38]:
df['Name'].str.lower()

0    vinay sharma
1      aman gupta
2      riya verma
3     priya singh
4      karan jain
Name: Name, dtype: str

In [39]:
df['Name'] = df['Name'].str.lower()

In [41]:
df

   Emp_ID          Name              Email Department  Salary
0     101  vinay sharma    vinay@gmail.com         IT   50000
1     102    aman gupta     aman@yahoo.com         HR   45000
2     103    riya verma     riya@gmail.com         IT   60000
3     104   priya singh  priya@outlook.com      Sales   55000
4     105    karan jain    karan@yahoo.com    Finance   70000

In [42]:
df[df['Email'].str.contains('gmail')]

   Emp_ID          Name            Email Department  Salary
0     101  vinay sharma  vinay@gmail.com         IT   50000
2     103    riya verma   riya@gmail.com         IT   60000

In [43]:
df['Email'].str.replace('gmail.com','googl.com')

0      vinay@googl.com
1       aman@yahoo.com
2       riya@googl.com
3    priya@outlook.com
4      karan@yahoo.com
Name: Email, dtype: str

In [44]:
df["Email"].str.split("@")

0      [vinay, gmail.com]
1       [aman, yahoo.com]
2       [riya, gmail.com]
3    [priya, outlook.com]
4      [karan, yahoo.com]
Name: Email, dtype: object

In [ ]:
## Aggregate function 
# sum,means,median, made , min , max, count , std 
# find the total salary padid to all the employees

np.int64(280000)

mean()

Find the average salary of employees.

median()

Find the median salary.

mode()

Find the most frequently occurring department.

min()

Find the minimum salary.

Find the employee having the minimum salary.

max()

Find the maximum salary.

Find the employee having the maximum salary.

count()

Count total employees.

Count how many salary records are present.

Count employees department-wise.

In [24]:
print(df['Salary'].mean())
print(df['Salary'].median())
print(df['Salary'].mode())
print(df['Salary'].std())
print(df['Salary'].max())
print(df['Salary'].min())
print(df['Emp_ID'].count())
print(df['Salary'].count())
print(df['Department'].count())

56000.0
55000.0
0    45000
1    50000
2    55000
3    60000
4    70000
Name: Salary, dtype: int64
9617.692030835673
70000
45000
5
5
5

### Group by in columns

In [25]:
import pandas as pd

df = pd.DataFrame({
    'Employee':['A','B','C','D','E','F'],
    'Department':['IT','HR','IT','HR','Sales','IT'],
    'Salary':[50000,45000,60000,55000,70000,65000]
})

df

  Employee Department  Salary
0        A         IT   50000
1        B         HR   45000
2        C         IT   60000
3        D         HR   55000
4        E      Sales   70000
5        F         IT   65000

In [27]:
df.groupby('Department')

In [28]:
# department wise avg salary
df.groupby('Department')['Salary'].min()

Department
HR       45000
IT       50000
Sales    70000
Name: Salary, dtype: int64

In [29]:
df.groupby('Department')['Salary'].max()

Department
HR       55000
IT       65000
Sales    70000
Name: Salary, dtype: int64

In [33]:
df.groupby('Department')['Employee'].count()

Department
HR       2
IT       3
Sales    1
Name: Employee, dtype: int64

In [34]:
 #group by in mutiple columns

df.groupby('Department')['Salary'].agg(['min','max','median','sum'])

              min    max   median     sum
Department
HR          45000  55000  50000.0  100000
IT          50000  65000  60000.0  175000
Sales       70000  70000  70000.0   70000

### mergei a common columns

In [51]:
emp = pd.DataFrame({
    'Emp_ID':[101,102,103],
    'Name':['Vinay','Aman','Riya']
})

In [52]:
salary = pd.DataFrame({
    'Emp_ID':[101,102,104],
    'Salary':[50000,45000,60000]
})

In [53]:
pd.merge(emp,salary, on='Emp_ID')

   Emp_ID   Name  Salary
0     101  Vinay   50000
1     102   Aman   45000

In [58]:
emp.join(salary,lsuffix="emp_id")

   Emp_IDemp_id   Name  Emp_ID  Salary
0           101  Vinay     101   50000
1           102   Aman     102   45000
2           103   Riya     104   60000

In [59]:
pd.merge(emp,salary, on='Emp_ID',how='outer')

   Emp_ID   Name   Salary
0     101  Vinay  50000.0
1     102   Aman  45000.0
2     103   Riya      NaN
3     104    NaN  60000.0

In [60]:
pd.merge(emp,salary, on='Emp_ID',how='inner')

   Emp_ID   Name  Salary
0     101  Vinay   50000
1     102   Aman   45000

In [61]:
import pandas as pd

df1 = pd.DataFrame({
    'Emp_ID': [101, 102],
    'Name': ['Vinay', 'Aman'],
    'Salary': [50000, 45000]
})

df2 = pd.DataFrame({
    'Emp_ID': [103, 104],
    'Name': ['Riya', 'Priya'],
    'Salary': [60000, 55000]
})

In [62]:
pd.concat([df1,df2],axis=0)

   Emp_ID   Name  Salary
0     101  Vinay   50000
1     102   Aman   45000
0     103   Riya   60000
1     104  Priya   55000

In [63]:
pd.concat([df1,df2],axis=1)

   Emp_ID   Name  Salary  Emp_ID   Name  Salary
0     101  Vinay   50000     103   Riya   60000
1     102   Aman   45000     104  Priya   55000